---
apiVersion: v1
kind: Service
metadata:
  name: python-statsd
  labels:
    app: python-statsd
spec:
  selector:
    app: python-statsd
  type: ClusterIP
  ports:
  - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-statsd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-statsd
    spec:
      containers:
      - name: python-statsd
        image: gcr.io/zing-registry-188222/zenoss/app-examples/python-statsd:latest
        command: [/venv/bin/python3, -m, python_statsd]
        env:
        - name: STATSD_HOST
          value: gostatsd
