version: '3'
services:
  gostatsd:
    image: zenoss/gostatsd:1.0.0
    environment:
      - GSD_VERBOSE=1
      - GSD_BACKENDS=zenoss
      - GSD_FLUSH_INTERVAL=10s
      - GSD_MAX_WORKERS=1
      - GSD_DEFAULT_TAGS=source-type:statsd source:${NAMESPACE:?err}.app-examples
      - GSD_INTERNAL_TAGS=app:${NAMESPACE:?err}.app-examples.statsd name:${NAMESPACE:?err}.app-examples.statsd simpleCustomRelationshipSourceTag.0:${NAMESPACE:?err}.app-examples.statsd
      - ZENOSS_ADDRESS=${ZENOSS_ADDRESS:?err}
      - ZENOSS_API_KEY=${ZENOSS_API_KEY:?err}
      - ZENOSS_METRIC_DIMENSION_TAGS=source app
      - ZENOSS_METRIC_METADATA_TAGS=source-type
      - ZENOSS_MODEL_DIMENSION_TAGS=source app
      - ZENOSS_MODEL_METADATA_TAGS=source-type name simpleCustomRelationshipSourceTag simpleCustomRelationshipSinkTag

  requester:
    build: ./requester
    command:
      - dotnet-statsd
      - go-metrics
      - java-metrics
      - node-statsd
      - python-metrology
      - python-relationship
      - python-statsd

  dotnet-statsd:
    build: ./dotnet-statsd
    environment:
      - STATSD_HOST=gostatsd

  go-metrics:
    build: ./go-metrics
    environment:
      - STATSD_HOST=gostatsd

  python-metrology:
    build: ./python-metrology
    environment:
      - STATSD_HOST=gostatsd
      - STATSD_INTERVAL=10

  python-relationship:
    build: ./python-relationship
    environment:
      - STATSD_HOST=gostatsd
      - RELATIONSHIP_SINK_TAGS=${NAMESPACE:?err}.app-examples.statsd

  python-statsd:
    build: ./python-statsd
    environment:
      - STATSD_HOST=gostatsd

  node-statsd:
    build: ./node-statsd
    environment:
      - STATSD_HOST=gostatsd

  java-metrics:
    build: ./java-metrics
    environment:
      - STATSD_HOST=gostatsd
