version: '3'
services:
  gostatsd:
    image: gcr.io/zing-registry-188222/zenoss/gostatsd:b76966fc
    environment:
      - GSD_VERBOSE=1
      - GSD_BACKENDS=zenoss
      - GSD_FLUSH_INTERVAL=10s
      - GSD_MAX_WORKERS=1
      - GSD_DEFAULT_TAGS=source-type:com.atlassian.gostatsd source:com.zenoss.app-examples.gostatsd.docker
      - GSD_INTERNAL_TAGS=contextUUID:com.zenoss.app-examples.gostatsd.docker name:gostatsd.app-examples simpleCustomRelationshipSourceTag.0:com.zenoss.app-examples.gostatsd.docker
      - ZENOSS_ADDRESS=${ZENOSS_ADDRESS:?err}
      - ZENOSS_API_KEY=${ZENOSS_API_KEY:?err}
      - ZENOSS_METRIC_DIMENSION_TAGS=source contextUUID
      - ZENOSS_METRIC_METADATA_TAGS=source-type
      - ZENOSS_MODEL_DIMENSION_TAGS=source contextUUID
      - ZENOSS_MODEL_METADATA_TAGS=source-type name simpleCustomRelationshipSourceTag simpleCustomRelationshipSinkTag

  requester:
    build: ./requester
    command:
      - dotnet-statsd
      - go-metrics
      - node-statsd
      - python-metrology
      - python-relationship
      - python-statsd

  dotnet-statsd:
    build: ./dotnet-statsd
    environment:
      - STATSD_HOST=gostatsd

  go-metrics:
    build: ./go-metrics
    environment:
      - STATSD_HOST=gostatsd

  python-metrology:
    build: ./python-metrology
    environment:
      - STATSD_HOST=gostatsd
      - STATSD_INTERVAL=10

  python-relationship:
    build: ./python-relationship
    environment:
      - STATSD_HOST=gostatsd
      - RELATIONSHIP_SINK_TAGS=com.zenoss.app-examples.gostatsd.docker

  python-statsd:
    build: ./python-statsd
    environment:
      - STATSD_HOST=gostatsd

  node-statsd:
    build: ./node-statsd
    environment:
      - STATSD_HOST=gostatsd
