---
apiVersion: v1
kind: Service
metadata:
  name: node-statsd
  labels:
    app: node-statsd
spec:
  selector:
    app: node-statsd
  type: ClusterIP
  ports:
  - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-statsd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-statsd
    spec:
      containers:
      - name: node-statsd
        image: gcr.io/zing-registry-188222/zenoss/app-examples/node-statsd:latest
        command: [npm, run, start]
        env:
        - name: STATSD_HOST
          value: gostatsd
