logging:
  level: INFO
  loggers:
    com.zenoss.example.javametrics: DEBUG

server:
  applicationConnectors:
  - type: http 
    port: 5000
  adminConnectors:
  - type: http
    port: 5001

statsDMetricTags:
  contextUUID: example.java.metrics
  meta_type: com.example.java.metrics
  name: Java Metrics Example
