---
apiVersion: v1
kind: Service
metadata:
  name: java-metrics
  labels:
    app: java-metrics
spec:
  selector:
    app: java-metrics
  type: ClusterIP
  ports:
  - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-metrics
    spec:
      containers:
      - name: java-metrics
        image: gcr.io/zing-registry-188222/zenoss/app-examples/java-metrics:latest
        command: [java, --add-opens, java.base/java.lang=ALL-UNNAMED, -jar, javametrics-1.0-SNAPSHOT-all.jar, server, config.yml]
        env:
        - name: STATSD_HOST
          value: gostatsd
