---
apiVersion: v1
kind: Service
metadata:
  name: go-metrics
  labels:
    app: go-metrics
spec:
  selector:
    app: go-metrics
  type: ClusterIP
  ports:
  - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-metrics
    spec:
      containers:
      - name: go-metrics
        image: gcr.io/zing-registry-188222/zenoss/app-examples/go-metrics:latest
        command: [/go-metrics]
        env:
        - name: STATSD_HOST
          value: gostatsd
