---
apiVersion: v1
kind: Service
metadata:
  name: python-metrology
  labels:
    app: python-metrology
spec:
  selector:
    app: python-metrology
  type: ClusterIP
  ports:
  - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-metrology
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-metrology
    spec:
      containers:
      - name: python-metrology
        image: gcr.io/zing-registry-188222/zenoss/app-examples/python-metrology:latest
        command: [/venv/bin/python3, -m, python_metrology]
        env:
        - name: STATSD_HOST
          value: gostatsd
