---
apiVersion: v1
kind: Service
metadata:
  name: python-relationship
  labels:
    app: python-relationship
spec:
  selector:
    app: python-relationship
  type: ClusterIP
  ports:
  - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-relationship
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-relationship
    spec:
      containers:
      - name: python-relationship
        image: gcr.io/zing-registry-188222/zenoss/app-examples/python-relationship:latest
        command: [/venv/bin/python3, -m, python_relationship]
        env:
        - name: STATSD_HOST
          value: gostatsd
        - name: RELATIONSHIP_SINK_TAGS
          value: com.zenoss.app-examples.gostatsd.kubernetes
        - name: KUBERNETES_CLUSTER
          value: app-examples-cluster
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_CONTAINER
          value: python-relationship
